### ISSUE TITLE
BindRPZ format throws an error

### ISSUE THREAD

**Issue by djacobuidaho** [csirtgadgets/verbose-robot-sdk-py#5]
# Do you have an active https://csirtg.io/support account ? :)
No

# Expected behavior and actual behavior.
`cif --itype fqdn --tags malware --probability 85 --format bindrpz` should output to stdout the rpz zone file contents, but I get an error:
```
Traceback (most recent call last):
  File "/usr/local/bin/cif", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/cifsdk/cli.py", line 290, in main
    _search(cli, args, options, filters)
  File "/usr/local/lib/python3.7/dist-packages/cifsdk/cli.py", line 106, in _search
    for l in FORMATS[fmt](data=sorted(rv, key=lambda i: i['reported_at']), cols=args.columns.split(',')):
TypeError: get_lines() got an unexpected keyword argument 'cols'
```
# Steps to reproduce the problem
```
pip install https://github.com/csirtgadgets/verbose-robot-sdk-py/archive/master.zip     # pip install 'cifsdk>=4.0.0a1,<5.0.0' doesn't seem to work currently
cif --itype fqdn --tags malware --probability 85 -f bindrpz
```
This should install cifsdk from the master branch (9fccee2) and csirtg_indicator 2.0a24.

# Relevant logs as a result of the actual behavior
N/A

# Specifications like the version of the project, operating system, or hardware.
Docker, and macOS Mojave

**Comment by djacobuidaho** [comment]
csirtg_indicator (silver-meme) bindrpz format plugin does not accept cols as an argument. Also, get_lines() does not return an iterable object.

**Comment by djacobuidaho** [comment]
I think this is an issue for silver-meme not verbose-robot-py...
