### ISSUE TITLE
Unable to submit new indicator. Submit is not an attribute of HTTP

### ISSUE THREAD

**Issue by krypto29s1972** [csirtgadgets/verbose-robot-sdk-py#8]
# Do you have an active https://csirtg.io/support account ? :)
Yes
# Expected behavior and actual behavior.

I am running Cifv4 Verbose-robot in a docker container. I am attempting to submit a new indicator to using the bellow example script. I have redacted my configuration information. When using cli.submit. I am getting the error.

ret = cli.submit(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'HTTP' object has no attribute 'submit'
##################################################

dir(cli) does infact show there is no submit attribute.
###################################################
import logging
from cifsdk.client.http import HTTP as Client

data = '{"indicator":"example4.com","tlp":"amber","confidence":"4","tags":"malware","provider":"example.com","group":"everyone"}'

cli = Client(token='1234',
            remote='https://localhost',
            verify_ssl=False)

ret = cli.submit(data)
print("submission id: {0}".format(ret))

# Steps to reporduce the problem

ret = cli.submit(data)
# Relevant logs as a result of the actual behavior

# Specifications like the version of the project, operating system, or hardware.

**Comment by wesyoung** [comment]
try this:

https://github.com/csirtgadgets/cifsdk-py-v4/wiki#create

i updated the doc a bit- tested, should work.

**Comment by krypto29s1972** [comment]
Wes,

Thank you for the quick response. I am getting a timeout error on submit from the response. Is that normal?

Oddly, it does successfully submit the indicator. It takes multiple seconds for the connection to close. I am sure putting a timeout in submit script would work around that. I wanted to see if that is expected behavior?

>>> import logging
>>> import json
>>> from cifsdk.client.http import HTTP as Client
>>> data = '{"indicator":"example4.com","tlp":"amber","confidence":"4","tags":"malware","provider":"example.com","group":"everyone"}'
>>> data = json.loads(data)
>>> cli = Client(token='redacted',
... remote='https://localhost',
... verify_ssl=False)
>>> ret = cli.indicators_create(data)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/cifsdk/client/http.py", line 286, in indicators_create
    rv = self._post('indicators', data)
  File "/usr/local/lib/python3.6/site-packages/cifsdk/client/http.py", line 189, in _post
    headers=headers, timeout=self.timeout)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
